version: '3.7'
services:
  test-database:
    container_name: postgres_test_db
    image: postgres
    environment:
      POSTGRES_PASSWORD: ${DB_TEST_PASSWORD}
      POSTGRES_USER: ${DB_TEST_USER}
      POSTGRES_DB: ${DB_TEST_NAME}
    expose:
      - 5432
    ports:
      - "5432:5432"
  test-migrations:
    container_name: test_migrations_runner
    build: ./migrations
    depends_on:
      - test-database
    volumes:
      - ./migrations:/migrations
    entrypoint: ["./wait-for-it.sh", "test-database:5432", "--", "migrate", "-path", "/migrations", "-database",  "postgres://${DB_TEST_USER}:${DB_TEST_PASSWORD}@test-database:5432/${DB_TEST_NAME}?sslmode=disable", "up"]
  integration-tests:
    container_name: integration_tests
    build:
      context: .
      dockerfile: Dockerfile.test
    depends_on:
      - test-database
      - test-migrations
    volumes:
      - ./logs.txt:/usr/src/app/logs.txt
    ports:
      - "8080:8080"
    entrypoint: ["./wait-for-it.sh", "test-database:5432", "--", "go", "test", "./...", "--tags=integration"]